# Generated by Django 2.0 on 2019-05-26 02:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Ingrese 9 dígitos', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('address', models.CharField(max_length=100, verbose_name='Dirección')),
                ('birthday', models.DateField(verbose_name='Cumpleaños')),
            ],
            options={
                'verbose_name': 'Amigo',
                'verbose_name_plural': 'Amigos',
                'ordering': ['first_name'],
            },
        ),
    ]
